"""Build a FAISS similarity index for content embeddings.

Usage
-----
    python -m embeddings.build_faiss_index

The embedding vectors generated by ``embeddings.build_embeddings`` are already
L2-normalized, so an inner-product FAISS index behaves like cosine similarity.
"""

from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

import faiss
import numpy as np
import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parents[1]

EMBEDDINGS_DIR = PROJECT_ROOT / "embeddings"
NPY_PATH = EMBEDDINGS_DIR / "content_embeddings.npy"
INDEX_CSV_PATH = EMBEDDINGS_DIR / "content_embedding_index.csv"
FAISS_INDEX_PATH = EMBEDDINGS_DIR / "content_faiss.index"
FAISS_METADATA_PATH = EMBEDDINGS_DIR / "content_faiss_metadata.json"


def build_faiss_index(
    npy_path: Path = NPY_PATH,
    index_csv_path: Path = INDEX_CSV_PATH,
    faiss_index_path: Path = FAISS_INDEX_PATH,
    metadata_path: Path = FAISS_METADATA_PATH,
) -> None:
    """Create and save a FAISS IndexFlatIP index from the embedding matrix."""
    if not npy_path.exists():
        raise FileNotFoundError(
            f"Embedding matrix not found: {npy_path}\n"
            "Run: python -m embeddings.build_embeddings"
        )
    if not index_csv_path.exists():
        raise FileNotFoundError(
            f"Embedding index CSV not found: {index_csv_path}\n"
            "Run: python -m embeddings.build_embeddings"
        )

    vectors = np.load(npy_path).astype(np.float32, copy=False)
    embedding_index = pd.read_csv(index_csv_path)

    _validate_inputs(vectors, embedding_index)

    dimension = vectors.shape[1]
    index = faiss.IndexFlatIP(dimension)
    index.add(np.ascontiguousarray(vectors))

    faiss_index_path.parent.mkdir(parents=True, exist_ok=True)
    faiss.write_index(index, str(faiss_index_path))

    metadata = {
        "created_at": datetime.now(timezone.utc).isoformat(),
        "index_type": "IndexFlatIP",
        "metric": "inner_product",
        "embedding_rows": int(vectors.shape[0]),
        "embedding_dimension": int(dimension),
        "source_embeddings": str(npy_path),
        "source_index": str(index_csv_path),
    }
    metadata_path.write_text(json.dumps(metadata, indent=2), encoding="utf-8")

    print("FAISS index saved:")
    print(f"  Index    : {faiss_index_path}")
    print(f"  Metadata : {metadata_path}")
    print(f"  Vectors  : {index.ntotal} rows x {dimension} dims")


def _validate_inputs(vectors: np.ndarray, embedding_index: pd.DataFrame) -> None:
    errors: list[str] = []

    if vectors.ndim != 2:
        errors.append(f"Embedding matrix must be 2D, got shape={vectors.shape}.")
    if vectors.dtype != np.float32:
        errors.append(f"Embedding matrix must be float32, got dtype={vectors.dtype}.")
    if len(embedding_index) != vectors.shape[0]:
        errors.append(
            "Row count mismatch: "
            f"CSV has {len(embedding_index)} rows, matrix has {vectors.shape[0]} rows."
        )
    if "embedding_row" not in embedding_index.columns:
        errors.append("CSV is missing required column: embedding_row.")
    elif list(embedding_index["embedding_row"]) != list(range(len(embedding_index))):
        errors.append("embedding_row must be a contiguous 0-based sequence.")
    if not np.isfinite(vectors).all():
        errors.append("Embedding matrix contains NaN or infinite values.")

    if errors:
        message = "\n".join(f"  - {error}" for error in errors)
        raise ValueError(f"Cannot build FAISS index:\n{message}")


def main() -> None:
    try:
        build_faiss_index()
    except (FileNotFoundError, ValueError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        raise SystemExit(1)


if __name__ == "__main__":
    main()
